network.host: 0.0.0.0
cluster.name: elasticsearch
discovery.zen.minimum_master_nodes: 1
configsync.config_path: /var/lib/elasticsearch/config
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
