services:
  search01:
    image: ghcr.io/codelibs/fess-opensearch:2.17.0
    container_name: search01
    environment:
      - node.name=search01
      - discovery.seed_hosts=search01,search02,search03
      - cluster.initial_cluster_manager_nodes=search01,search02,search03
      - cluster.name=fess-search
      - bootstrap.memory_lock=true
      - node.roles=cluster_manager,data,ingest,ml
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - search01_data:/usr/share/opensearch/data
      - search01_dictionary:/usr/share/opensearch/config/dictionary
    ports:
      - 9200:9200
    networks:
      - search_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

  search02:
    image: ghcr.io/codelibs/fess-opensearch:2.17.0
    container_name: search02
    environment:
      - node.name=search02
      - discovery.seed_hosts=search01,search02,search03
      - cluster.initial_cluster_manager_nodes=search01,search02,search03
      - cluster.name=fess-search
      - bootstrap.memory_lock=true
      - node.roles=cluster_manager,data,ingest,ml
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - search02_data:/usr/share/opensearch/data
      - search02_dictionary:/usr/share/opensearch/config/dictionary
    ports:
      - 9201:9200
    networks:
      - search_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    depends_on:
      - search01

  search03:
    image: ghcr.io/codelibs/fess-opensearch:2.17.0
    container_name: search03
    environment:
      - node.name=search03
      - discovery.seed_hosts=search01,search02,search03
      - cluster.initial_cluster_manager_nodes=search01,search02,search03
      - cluster.name=fess-search
      - bootstrap.memory_lock=true
      - node.roles=cluster_manager,data,ingest,ml
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - search03_data:/usr/share/opensearch/data
      - search03_dictionary:/usr/share/opensearch/config/dictionary
    ports:
      - 9202:9200
    networks:
      - search_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    depends_on:
      - search01
      - search02

  search04:
    image: ghcr.io/codelibs/fess-opensearch:2.17.0
    container_name: search04
    environment:
      - node.name=search04
      - discovery.seed_hosts=search01,search02,search03
      - cluster.initial_cluster_manager_nodes=search01,search02,search03
      - cluster.name=fess-search
      - bootstrap.memory_lock=true
      - node.roles=data,ingest,ml
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - search04_data:/usr/share/opensearch/data
      - search04_dictionary:/usr/share/opensearch/config/dictionary
    ports:
      - 9203:9200
    networks:
      - search_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    depends_on:
      - search01
      - search02
      - search03

  search05:
    image: ghcr.io/codelibs/fess-opensearch:2.17.0
    container_name: search05
    environment:
      - node.name=search05
      - discovery.seed_hosts=search01,search02,search03
      - cluster.initial_cluster_manager_nodes=search01,search02,search03
      - cluster.name=fess-search
      - bootstrap.memory_lock=true
      - node.roles=data,ingest,ml
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - search05_data:/usr/share/opensearch/data
      - search05_dictionary:/usr/share/opensearch/config/dictionary
    ports:
      - 9204:9200
    networks:
      - search_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    depends_on:
      - search01
      - search02
      - search03

volumes:
  search01_data:
    driver: local
  search01_dictionary:
    driver: local
  search02_data:
    driver: local
  search02_dictionary:
    driver: local
  search03_data:
    driver: local
  search03_dictionary:
    driver: local
  search04_data:
    driver: local
  search04_dictionary:
    driver: local
  search05_data:
    driver: local
  search05_dictionary:
    driver: local
