services:
  fess01:
    image: ghcr.io/codelibs/fess:snapshot
    container_name: fess01
    environment:
      # - "SEARCH_ENGINE_HTTP_URL=http://search01:9200,http://es02:9200,http://es03:9200,http://es04:9200,http://es05:9200"
      - "SEARCH_ENGINE_HTTP_URL=http://search01:9200"
      - "FESS_DICTIONARY_PATH=${FESS_DICTIONARY_PATH:-/usr/share/opensearch/config/dictionary/}"
    ports:
      - "8080:8080"
    networks:
      - search_net
    depends_on:
      - search01
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

networks:
  search_net:
    driver: bridge
