services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://es01:9200"
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - es01
    restart: unless-stopped
