services:
  fess01:
    environment:
      - "ES_HTTP_URL=http://es01:9200"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary/"
      - "FESS_JAVA_OPTS=-Dfess.system.storage.accesskey=AKIAIOSFODNN7EXAMPLE -Dfess.system.storage.secretkey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY -Dfess.system.storage.endpoint=http://minio01:9000 -Dfess.system.storage.bucket=fess"

  minio01:
    image: minio/minio
    container_name: minio01
    restart: always
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    volumes:
      - minio-data:/data
    networks:
      - esnet
    command: server /data
    restart: unless-stopped

volumes:
  minio-data:
    driver: local

